// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi21RgqHsrPS9HUrX7vyMG0fVfxVFUHoA',
    appId: '1:192254877669:web:e4ff9109778e6a5ae6990c',
    messagingSenderId: '192254877669',
    projectId: 'auth-e-commerce-69117',
    authDomain: 'auth-e-commerce-69117.firebaseapp.com',
    storageBucket: 'auth-e-commerce-69117.firebasestorage.app',
    measurementId: 'G-GF0G1X477C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATse4HtIabfCK6De28fbWL1Kww3aGrInc',
    appId: '1:192254877669:android:768fae9e1a86d773e6990c',
    messagingSenderId: '192254877669',
    projectId: 'auth-e-commerce-69117',
    storageBucket: 'auth-e-commerce-69117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXjJmb7tcUHuAr0Vlssqp0XXdrlU3BXGw',
    appId: '1:192254877669:ios:ded87947d82606dce6990c',
    messagingSenderId: '192254877669',
    projectId: 'auth-e-commerce-69117',
    storageBucket: 'auth-e-commerce-69117.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXjJmb7tcUHuAr0Vlssqp0XXdrlU3BXGw',
    appId: '1:192254877669:ios:ded87947d82606dce6990c',
    messagingSenderId: '192254877669',
    projectId: 'auth-e-commerce-69117',
    storageBucket: 'auth-e-commerce-69117.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi21RgqHsrPS9HUrX7vyMG0fVfxVFUHoA',
    appId: '1:192254877669:web:6defe5a4084ac86fe6990c',
    messagingSenderId: '192254877669',
    projectId: 'auth-e-commerce-69117',
    authDomain: 'auth-e-commerce-69117.firebaseapp.com',
    storageBucket: 'auth-e-commerce-69117.firebasestorage.app',
    measurementId: 'G-ME4RXEWXKJ',
  );
}
